# Activer les logs de debug pour Spring Security
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web=TRACE
logging.level.org.springframework.security.authentication=TRACE

logging.level.org.hibernate.SQL=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Niveau de log lobal
logging.level.root=DEBUG

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration