# ============================================
# LOGGING (niveau INFO pour la production)
# ============================================
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.com.formation.pharmacy_manager=INFO

# ============================================
# SPRING SECURITY
# ============================================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ============================================
# JWT
# ============================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:1200000}